name: Build and Push Docker Image
on:
  schedule:
  - cron: "*/10 * * * *"

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get nightly version
        run: echo "##[set-output name=nightly_version;]$(sh /build.sh)"
        id: get_nightly_version

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: brandoncc/neovim-nightly
          tags: ${{ steps.get_nightly_version.nightly_version }},latest
