name: Docker

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get nightly version
        run: |
          # Get the "created_at" timestamp of the nightly release and replace
          # : and - characters in it with underscores
          NIGHTLY_VERSION=$(sed 's,[:-],_,g' <(\
            curl -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/neovim/neovim/releases/tags/nightly \
            | grep created_at \
            | cut -d : -f 2,3 \
            | tr -d \" \
            | tr -d \  \
            | head -n 1))

          # story the value for future steps
          echo "##[set-output name=nightly_version;]$NIGHTLY_VERSION"
        id: get_nightly_version

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build image, push if build is successful
        run: |
          docker build \
          --build-arg NIGHTLY_VERSION=${{ steps.get_nightly_version.nightly_version }} \
          -t brandoncc/neovim-nightly:latest \
          -t brandoncc/neovim-nightly:${{ steps.get_nightly_version.nightly_version }} \
          . \
          && docker push brandoncc/neovim-nightly:latest
