name: Docker

on: push

  # schedule:
    # - cron: '*/5 * * * *'

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get nightly version
        run: |
          # Get the "created_at" timestamp of the nightly release and replace
          # : and - characters in it with underscores
          NIGHTLY_VERSION=$(sed 's,[:-],_,g' <(\
            curl -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/neovim/neovim/releases/tags/nightly \
            | grep created_at \
            | cut -d : -f 2,3 \
            | tr -d \" \
            | tr -d \  \
            | head -n 1))

          echo "$NIGHTLY_VERSION" > nightly_version.txt

          # story the value for future steps
          echo "::set-output name=nightly_version::$NIGHTLY_VERSION"
        id: get_nightly_version

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin


      - name: Build image, push if build is successful
        run: |
          SUCCESS=false
          NIGHTLY_VERSION=${{ steps.get_nightly_version.outputs.nightly_version  }}

          docker build \
          --build-arg NIGHTLY_VERSION=$NIGHTLY_VERSION \
          -t brandoncc/neovim-nightly:latest \
          -t brandoncc/neovim-nightly:$NIGHTLY_VERSION \
          . \
          && docker push brandoncc/neovim-nightly:latest \
          && docker push brandoncc/neovim-nightly:$NIGHTLY_VERSION \
          && SUCCESS=true

          [ SUCCESS ] \
            && sudo gem install rbnacl \
            && ENCRYPTED_SECRET=$(ruby encrypt_nightly_version.rb "$NIGHTLY_VERSION" "${{ secrets.PUBLIC_KEY }}") \
            && echo "encrypted_secret: $ENCRYPTED_SECRET" \
            && curl \
              -X PUT \
              -H "Accept: application/vnd.github.v3+json" \
              -H 'authorization: Bearer ${{ secrets.ACCESS_TOKEN }}' \
              https://api.github.com/repos/${{ github.repository }}/actions/secrets/LAST_NIGHTLY_TIMESTAMP \
              -d "{'encrypted_value':'$ENCRYPTED_SECRET', 'key_id': '${{ secrets.PUBLIC_KEY_ID }}'}"
